export const knownTokens = [
  {
    id: 1,
    name: 'QADSAN',
    asset: 'QADSAN:GAOLE7JSN4OB7344UCOOEGIHEQY2XNLCW6YHKOCGZLTDV4VRTXQM27QU',
    iconLink: './images/qadsan/qadsan.png',
  },
  {
    id: 2,
    name: 'INDEX',
    asset: 'INDEX:GAOLE7JSN4OB7344UCOOEGIHEQY2XNLCW6YHKOCGZLTDV4VRTXQM27QU',
    iconLink: './images/qadsan/index.png',
  },
  {
    id: 3,
    name: 'ALSET',
    asset: 'ALSET:GA4LXEHVL7WZOFL7KRQEZ36ASVNJFP6OHQRS6UQ36GFFGYS7ZZNAVBBJ',
    iconLink: './images/qadsan/tesla.png',
  },
  {
    id: 4,
    name: 'ELPPA',
    asset: 'ELPPA:GANJZG7S2TZKAQG5VP4ZCCWZYLVAX3YB5QITBMGZTFLOSNTE35ZDPETC',
    iconLink: './images/qadsan/apple.png',
  },
  {
    id: 5,
    name: 'KOOBECAF',
    asset: 'KOOBECAF:GC36VPQFLYRBRZ34FLOMT72VJGQBMGUMT2QLIT32XOIP4TR34V74D5IH',
    iconLink: './images/qadsan/facebook.png',
  },
  {
    id: 6,
    name: 'ELGOOG',
    asset: 'ELGOOG:GBVKFKU77FCA75TQ6EYAUKIZG4NJL5NTMU3I3YJJI3MQUMG2GLH44EM4',
    iconLink: './images/qadsan/google.png',
  },
  {
    id: 7,
    name: 'LAPYAP',
    asset: 'LAPYAP:GA25AUGGORR7SQT3FGENZ35GMZI444QS7DHTUUJHUZ7IIMX4A4D6ATA2',
    iconLink: './images/qadsan/paypal.png',
  },
  {
    id: 8,
    name: 'EKIN',
    asset: 'EKIN:GCSDHUTR6YQZVN7HV3GVJJAHQ2LBYKJJMWCNJYHLB2XSUXLXQPS5IVEJ',
    iconLink: './images/qadsan/nike.png',
  },
  {
    id: 9,
    name: 'TFOSORCIM',
    asset: 'TFOSORCIM:GCC2J6OJAAGJ6OMTOI5MIJMNQ2ONCFKCVYISORBBEEXCBGXYCG6ZP5EG',
    iconLink: './images/qadsan/microsoft.png',
  },
  {
    id: 10,
    name: 'ISPEP',
    asset: 'ISPEP:GBGOBGXU5AGHADC6H7KGMEPXEIOJY7ZKIKLBTU363OCQTZNPTGNTVQJK',
    iconLink: './images/qadsan/pepsi.png',
  },
  {
    id: 11,
    name: 'ASIV',
    asset: 'ASIV:GDO7QNI3HTR76XGHLT3IROR5IKJ52CM2CWA5L2TXBKJWQV7OFLKIWCG3',
    iconLink: './images/qadsan/visa.png',
  },
  {
    id: 12,
    name: 'MARGELET',
    asset: 'MARGELET:GA5PB5WXXE4GTJWCDOPJPACFO7KC5IIIOO356XUCP37JPRDHJ2DL4AFI',
    iconLink: './images/qadsan/telegram.png',
  },
  {
    id: 13,
    name: 'NOZAMA',
    asset: 'NOZAMA:GDVA6YXBBNA7ONRYIWQDVSZC366EU5HQIBKPY4PNM4QBVSDJCKYMF2EE',
    iconLink: './images/qadsan/amazon.png',
  },
  {
    id: 14,
    name: 'BINC',
    asset: 'BINC:GDXYOVUNAH4KGTOUPPBHRJLANMMRKBOFR5LJCFKAG3U5AAXPA424WOWQ',
    iconLink: './images/bincome/binc.png',
  },
  {
    id: 15,
    name: 'BINCOME',
    asset: 'BINCOME:GB47S227MZ37TLYO2RD5EH4IT2DVWH7RRC67Z2VAKMV4TKFDF4GWYBLY',
    iconLink: './images/bincome/bincomedark.png',
  },
  {
    id: 16,
    name: 'USD',
    asset: 'USD:GAQTQSTVA6QWZSWTE4CVZLU6XDP3H3DVEXIIG2XMZGMLY3XCY5GZMNMI',
    iconLink: './images/centus/usd.svg',
  },
  {
    id: 17,
    name: 'CENTUS',
    asset: 'CENTUS:GCBSY6IJHRG4APD7EYZSULW62U3G2YLIVB3ZEPUO5KYAI7HVEOYFIBRI',
    iconLink: './images/centus/centus.svg',
  },
  {
    id: 18,
    name: 'CENTUSX',
    asset: 'CENTUSX:GD7I4VIGF2LJEK6XKZDFLWRT6NFVIXN2CGLVSXEPNWJWTN4QRGX4226Z',
    iconLink: './images/centus/centusx.svg',
  },
  {
    id: 19,
    name: 'STABLECENT',
    asset: 'STABLECENT:GCML5PV7VISAJOM3K3YS25PTETL2NY7PAAAREDKY62WWP4XFTNGBJRL6',
    iconLink: 'https://stablecent.one/stablecent.png',
  },
  {
    id: 20,
    name: 'BONUS',
    asset: 'BONUS:GCP7IKROLJVDTQC34CNZGL6OAAWJ62H5MO3IST7CTOEYK7GWRR4CHDUH',
    iconLink: './images/centus/bonus.svg',
  },
  {
    id: 21,
    name: 'DEPO',
    asset: 'DEPO:GC7J3ZOQ4GG4QKS57JQOQQWAP636GCO6JFL5HTJRVNRWILAAM6BDSKLX',
    iconLink: 'https://centus.fund/image/Depo_logo.png',
  },
  {
    id: 22,
    name: 'DBC',
    asset: 'DBC:GDGHJL32AYPBNKLJQXWEASJVXBDWS2JO7LICIMGS4JVIPXH6KGO5SQBS',
    iconLink: './images/centus/dbc.svg',
  },
  {
    id: 23,
    name: 'WARRANT',
    asset: 'WARRANT:GA6SAVZCCTBKXK6QNA4FOTLX6MUJLUCQRE3NA7FQDTZFNQHDJRLENHDA',
    iconLink: 'https://centus.one/warrant.png',
  },
  {
    id: 24,
    name: 'AQUA',
    asset: 'AQUA:GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA',
    iconLink: 'https://aqua.network/assets/img/aqua-logo.png',
  },
  {
    id: 25,
    name: 'USDC',
    asset: 'USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN',
    iconLink: 'https://www.centre.io/images/usdc/usdc-icon-86074d9d49.png',
  },
];